import { NextRequest, NextResponse } from "next/server";
import { authenticateRequest, isAuthEnforced } from "@/lib/serverAuth";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { normalizePrivacyPreferences } from "@/lib/privacyPreferences";

const unavailable = () => NextResponse.json({ error: "Secure conversation storage is temporarily unavailable." }, { status: 503 });
const serialize = (row: Record<string, unknown>) => {
  const lastMessage = String(row.last_message || ""); const stored = String(row.title || "New Chat");
  const title = ["New Chat", "New Conversation", "Untitled"].includes(stored) && lastMessage ? `${lastMessage.split(/\s+/).slice(0, 5).join(" ")}${lastMessage.split(/\s+/).length > 5 ? "..." : ""}`.slice(0, 30) : stored;
  return { id: row.id, userId: row.user_id, title, type: row.type === "counsellor" ? "counsellor" : "ai_support", status: row.status || "active", retentionMode: row.retention_mode === "session" ? "session" : "account", lastMessage, messageCount: Number(row.message_count || 0), createdAt: row.created_at, updatedAt: row.updated_at };
};
export async function GET(request: NextRequest) { if (!isAuthEnforced()) return unavailable(); const auth = await authenticateRequest(request); if (auth.status !== "verified") return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const { data, error } = await getSupabaseAdmin().from("conversations").select("*").eq("user_id", auth.uid).order("updated_at", { ascending: false }); if (error) return unavailable(); return NextResponse.json({ conversations: (data || []).map((row) => serialize(row)) }); }
export async function POST(request: NextRequest) { if (!isAuthEnforced()) return unavailable(); const auth = await authenticateRequest(request); if (auth.status !== "verified") return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const body = await request.json().catch(() => ({})); const title = typeof body.title === "string" ? body.title.trim().slice(0, 80) : "New Chat"; const db = getSupabaseAdmin(); const { data: profile, error: profileError } = await db.from("profiles").select("privacy_preferences").eq("id", auth.uid).maybeSingle(); if (profileError || !profile) return unavailable(); const retentionMode = normalizePrivacyPreferences(profile.privacy_preferences).conversationRetention; const { data, error } = await db.from("conversations").insert({ user_id: auth.uid, title: title || "New Chat", type: "ai_support", retention_mode: retentionMode }).select("*").single(); if (error || !data) return unavailable(); return NextResponse.json({ conversation: serialize(data) }, { status: 201 }); }
export async function DELETE(request: NextRequest) { if (!isAuthEnforced()) return unavailable(); const auth = await authenticateRequest(request); if (auth.status !== "verified") return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const { error } = await getSupabaseAdmin().from("conversations").delete().eq("user_id", auth.uid).eq("retention_mode", "session"); return error ? unavailable() : NextResponse.json({ success: true }); }
