import { NextRequest, NextResponse } from "next/server";
import { authenticateRequest, isAuthEnforced } from "@/lib/serverAuth";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";

const unavailable = () => NextResponse.json({ success: false, error: "Secure conversation storage is temporarily unavailable." }, { status: 503 });
const message = (row: Record<string, unknown>) => ({ id: row.id, conversationId: row.conversation_id, sender: row.sender === "user" ? "user" : "ai", content: String(row.content || ""), timestamp: row.created_at, read: Boolean(row.read) });
async function authorized(request: NextRequest, context: { params: Promise<{ conversationId: string }> }) { if (!isAuthEnforced()) return { error: unavailable() }; const auth = await authenticateRequest(request); if (auth.status !== "verified") return { error: NextResponse.json({ error: "Authentication required" }, { status: 401 }) }; const { conversationId } = await context.params; if (!conversationId || conversationId.startsWith("local-")) return { error: NextResponse.json({ error: "Invalid conversation" }, { status: 400 }) }; const db = getSupabaseAdmin(); const { data, error } = await db.from("conversations").select("*").eq("id", conversationId).eq("user_id", auth.uid).maybeSingle(); if (error) return { error: unavailable() }; if (!data) return { error: NextResponse.json({ error: "Conversation not found" }, { status: 404 }) }; return { auth, db, conversationId, conversation: data }; }
export async function GET(request: NextRequest, context: { params: Promise<{ conversationId: string }> }) { const result = await authorized(request, context); if ("error" in result) return result.error; const { data, error } = await result.db.from("messages").select("*").eq("conversation_id", result.conversationId).order("created_at", { ascending: true }).limit(200); if (error) return unavailable(); return NextResponse.json({ messages: (data || []).map(message) }); }
export async function POST(request: NextRequest, context: { params: Promise<{ conversationId: string }> }) { const result = await authorized(request, context); if ("error" in result) return result.error; const body = await request.json().catch(() => ({})); const sender = body.sender === "user" ? "user" : body.sender === "ai" ? "ai" : null; const content = typeof body.content === "string" ? body.content.trim() : ""; if (!sender || !content || content.length > 8000) return NextResponse.json({ error: "Invalid message" }, { status: 400 }); const placeholder = ["New Chat", "New Conversation", "Untitled"].includes(String(result.conversation.title)); const generated = `${content.split(/\s+/).slice(0, 5).join(" ")}${content.split(/\s+/).length > 5 ? "..." : ""}`.slice(0, 30); const { data, error } = await result.db.from("messages").insert({ conversation_id: result.conversationId, sender, content, read: sender === "ai" }).select("*").single(); if (error || !data) return unavailable(); const update: Record<string, unknown> = { last_message: content.slice(0, 100), message_count: Number(result.conversation.message_count || 0) + 1 }; if (sender === "user" && placeholder) update.title = generated; await result.db.from("conversations").update(update).eq("id", result.conversationId); return NextResponse.json({ message: message(data) }, { status: 201 }); }
export async function PATCH(request: NextRequest, context: { params: Promise<{ conversationId: string }> }) { const result = await authorized(request, context); if ("error" in result) return result.error; const body = await request.json().catch(() => ({})); const title = typeof body.title === "string" ? body.title.trim().slice(0, 80) : ""; if (!title) return NextResponse.json({ error: "Invalid title" }, { status: 400 }); const { error } = await result.db.from("conversations").update({ title }).eq("id", result.conversationId); return error ? unavailable() : NextResponse.json({ success: true }); }
export async function DELETE(request: NextRequest, context: { params: Promise<{ conversationId: string }> }) { const result = await authorized(request, context); if ("error" in result) return result.error; const { error } = await result.db.from("conversations").delete().eq("id", result.conversationId); return error ? unavailable() : NextResponse.json({ success: true }); }
