/** Server-side Supabase data layer. All callers have authenticated a request. */
import { getSupabaseAdmin } from "../supabaseAdmin";
import { calculateNextPeriod, getCurrentPhase } from "../cycle";
import { rankCounsellors } from "../counsellorMatching";
import { evaluateCounsellorEligibility } from "../counsellorOperations";
import { AgentEvent, Counsellor, CounsellorSpecialty, CounsellorStatus, CycleData, PregnancyData, Reminder, SymptomLog, TriageSeverity, UserProfile } from "@/types";

type Json = Record<string, unknown>;
const admin = () => getSupabaseAdmin();
const iso = (date: Date | undefined) => date?.toISOString();
const date = (value: unknown, fallback = new Date()) => value ? new Date(value as string) : fallback;
const ensure = <T>(value: T | null, label: string): T => { if (!value) throw new Error(`Missing ${label}`); return value; };
const check = (error: { message?: string } | null) => { if (error) throw new Error(error.message); };

function profile(row: Json): UserProfile {
  const cycle = row.cycle_data as Json | null;
  const pregnancy = row.pregnancy_data as Json | null;
  return {
    uid: row.id as string, email: (row.email as string) || "", displayName: row.display_name as string | null,
    photoURL: row.photo_url as string | null, createdAt: date(row.created_at), updatedAt: date(row.updated_at),
    onboardingCompleted: Boolean(row.onboarding_completed), preferences: row.preferences as UserProfile["preferences"],
    registrationIntent: row.registration_intent === "counsellor" ? "counsellor" : "member",
    cycleData: cycle ? { ...(cycle as unknown as CycleData), lastPeriodDate: date(cycle.lastPeriodDate), nextPeriodDate: date(cycle.nextPeriodDate) } : null,
    pregnancyData: pregnancy ? { ...(pregnancy as unknown as PregnancyData), estimatedDueDate: pregnancy.estimatedDueDate ? date(pregnancy.estimatedDueDate) : undefined, lastMenstrualPeriodDate: pregnancy.lastMenstrualPeriodDate ? date(pregnancy.lastMenstrualPeriodDate) : undefined, conceptionDate: pregnancy.conceptionDate ? date(pregnancy.conceptionDate) : undefined, birthDate: pregnancy.birthDate ? date(pregnancy.birthDate) : undefined } : null,
  };
}
function counsellor(row: Json): Counsellor & { lastHeartbeat?: Date } {
  return { ...(row.profile as Json), id: row.id as string, status: row.status as CounsellorStatus, verified: row.verification_status === "verified", verificationStatus: row.verification_status as Counsellor["verificationStatus"], acceptingNewSessions: Boolean(row.accepting_new_sessions), maxConcurrentSessions: row.max_concurrent_sessions as number, createdAt: date(row.created_at), lastHeartbeat: row.last_heartbeat ? date(row.last_heartbeat) : undefined } as Counsellor & { lastHeartbeat?: Date };
}
async function getProfile(uid: string) { const { data, error } = await admin().from("profiles").select("*").eq("id", uid).maybeSingle(); check(error); return data as Json | null; }
async function updateProfile(uid: string, patch: Json) { const { error } = await admin().from("profiles").update(patch).eq("id", uid); check(error); }
async function addRecord(userId: string, recordType: string, payload: Json) { const { data, error } = await admin().from("user_records").insert({ user_id: userId, record_type: recordType, payload }).select("id").single(); check(error); return ensure(data, "record").id as string; }
async function findRecords(userId: string, recordType: string) { const { data, error } = await admin().from("user_records").select("*").eq("user_id", userId).eq("record_type", recordType).order("created_at", { ascending: false }); check(error); return (data || []) as Json[]; }

export async function saveCycleData(uid: string, cycleData: Partial<CycleData>) { const existing = await getProfile(uid); if (!existing) throw new Error("Cannot update cycle data because the user profile is missing"); const old = (existing.cycle_data as Json) || {}; await updateProfile(uid, { cycle_data: { ...old, ...cycleData, lastPeriodDate: iso(cycleData.lastPeriodDate) || old.lastPeriodDate, nextPeriodDate: iso(cycleData.nextPeriodDate) || old.nextPeriodDate } }); }
export async function getConversationMemory(uid: string, conversationId: string, maximumMessages = 50): Promise<Array<{ role: "user" | "assistant"; content: string }>> { const { data: conversation, error: ownerError } = await admin().from("conversations").select("id").eq("id", conversationId).eq("user_id", uid).maybeSingle(); check(ownerError); if (!conversation) return []; const { data, error } = await admin().from("messages").select("sender, content").eq("conversation_id", conversationId).order("created_at", { ascending: false }).limit(Math.min(Math.max(maximumMessages, 1), 50)); check(error); return (data || []).reverse().flatMap((message) => typeof message.content === "string" && message.content.trim() ? [{ role: message.sender === "user" ? "user" : "assistant" as const, content: message.content.trim().slice(0, 4000) }] : []); }
export async function savePregnancyData(uid: string, input: Partial<PregnancyData>) { const existing = await getProfile(uid); if (!existing) throw new Error("Cannot update pregnancy data because the user profile is missing"); const old = (existing.pregnancy_data as Json) || {}; await updateProfile(uid, { pregnancy_data: { ...old, ...input, isPregnant: input.isPregnant ?? old.isPregnant ?? false, gaveBirth: input.gaveBirth ?? old.gaveBirth ?? false, estimatedDueDate: iso(input.estimatedDueDate) || old.estimatedDueDate, lastMenstrualPeriodDate: iso(input.lastMenstrualPeriodDate) || old.lastMenstrualPeriodDate, conceptionDate: iso(input.conceptionDate) || old.conceptionDate, birthDate: iso(input.birthDate) || old.birthDate, updatedAt: new Date().toISOString(), createdAt: old.createdAt || new Date().toISOString() } }); }
export async function clearPregnancyData(uid: string) { await updateProfile(uid, { pregnancy_data: null }); }
export async function updateCycleAfterBirth(uid: string, birthDate: Date, cycleLength = 28, periodLength = 5) { const nextPeriodDate = calculateNextPeriod(birthDate, cycleLength); const { phase } = getCurrentPhase(birthDate, cycleLength, periodLength); await updateProfile(uid, { pregnancy_data: null, cycle_data: { lastPeriodDate: iso(birthDate), cycleLength, periodLength, nextPeriodDate: iso(nextPeriodDate), currentPhase: phase, symptoms: [], history: [] } }); }
export async function logSymptoms(uid: string, input: Omit<SymptomLog, "id">) { return addRecord(uid, "symptom", { ...input, date: iso(input.date) }); }
export async function getSymptoms(uid: string, startDate: Date, endDate: Date): Promise<SymptomLog[]> { return (await findRecords(uid, "symptom")).map((row) => ({ id: row.id as string, ...(row.payload as Json), date: date((row.payload as Json).date) } as SymptomLog)).filter((item) => item.date >= startDate && item.date <= endDate); }
export async function createReminder(uid: string, input: Omit<Reminder, "id" | "sent" | "read">) { return addRecord(uid, "reminder", { ...input, scheduledFor: iso(input.scheduledFor), sent: false, read: false }); }
export async function pausePeriodReminders(uid: string) { const entries = await findRecords(uid, "reminder"); await Promise.all(entries.filter((entry) => { const item = entry.payload as Json; return !item.sent && (item.type === "period_coming" || item.type === "period_start"); }).map((entry) => admin().from("user_records").update({ payload: { ...(entry.payload as Json), sent: true, read: true, cancelledAt: new Date().toISOString(), cancellationReason: "pregnancy_mode" } }).eq("id", entry.id))); }
export async function logAgentEvent(params: { userId: string; type: AgentEvent["type"]; severity?: TriageSeverity; conversationId?: string; success?: boolean }) { return addRecord(params.userId, "agent_event", { ...params, success: params.success ?? true }); }

async function getOrCreateConversation(uid: string, type: "ai_support" | "counsellor") { const { data, error } = await admin().from("conversations").select("id").eq("user_id", uid).eq("type", type).eq("status", "active").order("updated_at", { ascending: false }).limit(1).maybeSingle(); check(error); if (data) return data.id as string; const { data: created, error: createError } = await admin().from("conversations").insert({ user_id: uid, type }).select("id").single(); check(createError); return ensure(created, "conversation").id as string; }
export async function connectUserToCounsellor(params: { userId: string; counsellorId: string; reason: "user_request" | "risk_detected"; summary: string }) { const id = await getOrCreateConversation(params.userId, "counsellor"); const { error } = await admin().from("conversations").update({ title: "Counsellor Support", active_counsellor_id: params.counsellorId, status: "active" }).eq("id", id); check(error); return id; }
export async function setActiveCounsellorOnConversation(params: { conversationId: string; counsellor: Counsellor }) { const { error } = await admin().from("conversations").update({ active_counsellor_id: params.counsellor.id }).eq("id", params.conversationId); check(error); }
export async function getActiveCounsellorForConversation(conversationId: string) { const { data, error } = await admin().from("conversations").select("active_counsellor_id").eq("id", conversationId).maybeSingle(); check(error); if (!data?.active_counsellor_id) return null; const { data: row, error: rowError } = await admin().from("counsellors").select("*").eq("id", data.active_counsellor_id).maybeSingle(); check(rowError); if (!row) return null; const value = counsellor(row as Json); return { id: value.id, name: value.name, title: value.title, languages: value.languages, specializations: value.specializations, phoneNumber: value.phoneNumber, whatsappNumber: value.whatsappNumber }; }

export async function getCounsellors(): Promise<Counsellor[]> { const { data, error } = await admin().from("counsellors").select("*"); check(error); return (data || []).map((row) => counsellor(row as Json)).sort((a, b) => b.rating - a.rating); }
export async function getLiveCounsellors(): Promise<Counsellor[]> { const [staff, sessions] = await Promise.all([getCounsellors(), admin().from("counselling_sessions").select("counsellor_id").in("state", ["matched", "accepted", "active"])]); check(sessions.error); const assigned = new Set((sessions.data || []).map((row) => row.counsellor_id).filter(Boolean)); const cutoff = Date.now() - 120000; return staff.map((item) => { const heartbeat = (item as Counsellor & { lastHeartbeat?: Date }).lastHeartbeat; const operational = evaluateCounsellorEligibility(item, { activeLoad: assigned.has(item.id) ? 1 : 0, priority: "normal" }).eligible; return { ...item, status: assigned.has(item.id) ? "in_session" : operational && heartbeat && heartbeat.getTime() >= cutoff ? "available" : "offline" }; }); }
async function loads() { const { data, error } = await admin().from("counselling_sessions").select("counsellor_id").in("state", ["matched", "accepted", "active"]); check(error); return (data || []).reduce((map, row) => { if (row.counsellor_id) map.set(row.counsellor_id, (map.get(row.counsellor_id) || 0) + 1); return map; }, new Map<string, number>()); }
export async function routeCounsellor(params: { specialty?: CounsellorSpecialty; preferredLanguage?: string }): Promise<Counsellor | null> { let list = (await getLiveCounsellors()).filter((item) => item.status === "available" && (!params.specialty || item.specializations.includes(params.specialty))); if (params.preferredLanguage) { const matching = list.filter((item) => item.languages.some((language) => language.toLowerCase() === params.preferredLanguage?.toLowerCase())); if (matching.length) list = matching; } return rankCounsellors(list, params, await loads()); }
export async function batchUpdateCounsellorAvailability() { const values = await getLiveCounsellors(); await Promise.all(values.map((item) => admin().from("counsellors").update({ status: item.status }).eq("id", item.id))); return { updated: values.length, errors: 0 }; }

export async function updateAgentManagedProfile(uid: string, input: { displayName?: string; language?: "en" | "lg"; reminderDaysBefore?: number; emailNotifications?: boolean; pushNotifications?: boolean; theme?: "light" | "dark" | "system" }) { const row = ensure(await getProfile(uid), "profile"); const preferences = { ...((row.preferences as Json) || {}) }; if (input.displayName !== undefined) { const name = input.displayName.trim().slice(0, 80); if (!name) throw new Error("Display name cannot be empty"); await updateProfile(uid, { display_name: name }); } if (input.language !== undefined) preferences.language = input.language; if (input.reminderDaysBefore !== undefined) { const days = Math.round(input.reminderDaysBefore); if (days < 0 || days > 14) throw new Error("Reminder days must be between 0 and 14"); preferences.reminderDaysBefore = days; } if (input.emailNotifications !== undefined) preferences.emailNotifications = input.emailNotifications; if (input.pushNotifications !== undefined) preferences.pushNotifications = input.pushNotifications; if (input.theme !== undefined) preferences.theme = input.theme; if (Object.keys(input).some((key) => key !== "displayName")) await updateProfile(uid, { preferences }); }
export async function getAgentSystemOverview(uid: string) { const [row, sessions, symptoms] = await Promise.all([getProfile(uid), admin().from("counselling_sessions").select("id", { count: "exact", head: true }).eq("user_id", uid).in("state", ["requested", "matched", "accepted", "active"]), admin().from("user_records").select("id", { count: "exact", head: true }).eq("user_id", uid).eq("record_type", "symptom")]); check(sessions.error); check(symptoms.error); return { profile: row ? profile(row) : null, activeSessions: sessions.count || 0, recentSymptoms: symptoms.count || 0 }; }
