"use client";

import { useCallback, useEffect, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { auth } from "@/lib/authClient";
import { readApiResponse } from "@/lib/apiResponse";

type Article = { id: string; title: string; description: string; content: string; category: string; tags: string[]; authorName: string; authorTitle: string };
async function api(path: string, init?: RequestInit) { const token = await auth.currentUser?.getIdToken(); return fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: token ? `Bearer ${token}` : "", ...init?.headers } }); }

export default function AdminArticlesPage() {
  const [articles, setArticles] = useState<Article[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { try { const response = await api("/api/admin/articles"); const result = await readApiResponse<any>(response); if (!response.ok) throw new Error(result.error || "Could not load review queue"); setArticles(result.data.articles || []); setError(""); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Could not load review queue"); } }, []);
  useEffect(() => { load(); }, [load]);
  const review = async (articleId: string, decision: "publish" | "reject") => { setBusy(articleId); try { const response = await api("/api/admin/articles", { method: "PATCH", body: JSON.stringify({ articleId, decision }) }); const result = await readApiResponse<any>(response); if (!response.ok) throw new Error(result.error || "Review failed"); await load(); } catch (reviewError) { setError(reviewError instanceof Error ? reviewError.message : "Review failed"); } finally { setBusy(""); } };
  return <AdminShell><span className="eyebrow">Clinical editorial review</span><h1 className="mt-1 text-3xl font-extrabold text-text-primary dark:text-white">Library publication queue</h1><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">Review counsellor-submitted content before it reaches members.</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-5">{articles.length ? articles.map((article) => <article key={article.id} className="rounded-3xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-card-dark"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-semibold text-primary">{article.category}</span><h2 className="mt-3 text-xl font-bold text-gray-900 dark:text-white">{article.title}</h2><p className="mt-1 text-sm text-gray-600 dark:text-gray-300">By {article.authorName} · {article.authorTitle}</p></div></div><p className="mt-4 text-sm font-medium text-gray-700 dark:text-gray-200">{article.description}</p><div className="mt-4 whitespace-pre-line rounded-2xl bg-gray-50 p-4 text-sm leading-6 text-gray-700 dark:bg-gray-800 dark:text-gray-200">{article.content}</div><div className="mt-4 flex gap-3"><button disabled={busy === article.id} onClick={() => review(article.id, "publish")} className="rounded-xl bg-green-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Publish</button><button disabled={busy === article.id} onClick={() => review(article.id, "reject")} className="rounded-xl border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 disabled:opacity-50">Reject</button></div></article>) : <p className="rounded-3xl border border-dashed border-gray-300 p-10 text-center text-sm text-gray-500 dark:border-gray-700">No articles are waiting for review.</p>}</div></AdminShell>;
}
